version: '3'

services: 
  python: 
    build: ./app
    volumes: 
      - ./app:/usr/src/app
    ports: 
      - 5000:80
#    depends_on:
#      - postgresql
#  postgresql:
#    build: ./postgresql
#    ports:
#      - 5432:5432