version: '3'

services: 
  python:
    container_name: 'python_service'
    hostname: 'python'
    build: ./python
    ports:
      - 5000:5000
    volumes: 
      - ./python:/usr/src/app
    depends_on:
      - postgresql
      - redis
  postgresql:
    container_name: 'postgresql_service'
    hostname: 'postgresql'
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
  redis:
    container_name: 'redis_service'
    hostname: 'redis'
    image: redis:6
    ports:
      - 6379:6379
    volumes: 
      - ./redis-data:/data