version: '3'

services: 
  python: 
    build: ./python
    volumes: 
      - ./python:/usr/src/app
    ports: 
      - 5000:5000
    depends_on:
      - postgresql
  postgresql:
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - 6379:6379